import type { Metadata } from "next";
import { Cormorant_Garamond } from "next/font/google";
import "./globals.scss";
import Script from "next/script";

const cormorantCormorant = Cormorant_Garamond({
  variable: "--font-cormorant",
  subsets: ["cyrillic"],
  weight: ["300"],
  style: ["normal", "italic"],
});
const cormorantCormorantBold = Cormorant_Garamond({
  variable: "--font-cormorant-bold",
  subsets: ["cyrillic"],
  weight: ["700"],
  style: ["normal"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${cormorantCormorant.variable} ${cormorantCormorantBold.variable}`}
      >
        {children}
        <Script
          src="https://api-maps.yandex.ru/v3/?apikey=c9dc0e1b-b835-4995-9ffe-b07128f15143&lang=ru_RU"
          strategy="beforeInteractive"
        />
      </body>
    </html>
  );
}
